spring:
  application:
    profile: default
    environment: default
my:
  greeting: Hello World from config server
  list:
    values: One, Two, Three
db:
  connection: somestring-configserver
  host: 127.0.0.1
  port: 1200
